language: node_js
node_js:
  - "11.0.0"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli@7.0.6
install: npm install
script:
  - npm run test
  - npm run lint
  - npm run build
